Task 77 - Add terms
uwstout-cs458-s22/advisor002 pull request #84
Opened 2022-04-07 20:52 UTC by presmiks18

2022-04-07 22:56 UTC, Pirundy approved these changes
Looks good make sure to work on the merge conflicts

2022-04-10 09:49 UTC, Pirundy requested changes
Looks like you need to have some assertions in your test or remove the test in order for the merge to go through on terms.test.js. This is on line 60-70 for reference.

2022-04-11 17:31 UTC, ColeLindner approved these changes
Test doesnt do anything but good enough to be shown in presentation.

2022-04-11 17:55 UTC, Pirundy approved these changes

2022-04-11 17:56 UTC, merged